[project]
name = "document-service"
version = "0.1.1"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "pydantic-settings>=2.13.1",
    "dishka>=1.10.0",
    "fastapi>=0.135.2",
    "uvicorn>=0.47.0",
]

[project.optional-dependencies]
mongo = [
    "beanie>=2.1.0",
]

[dependency-groups]
tests = [
    "pytest>=9.0.3",
]
