name: CI

on:
  pull_request:
    branches: [ main, dev ]

env:
  PYTHON_VERSION: '3.14'
  UV_VERSION: '0.10.7'

jobs:
  ruff:
    if: github.base_ref == 'dev' || github.base_ref == 'main'
    uses: ./.github/workflows/ruff.yml
    with:
      python-version: ${{ vars.PYTHON_VERSION }}
      uv-version: ${{ vars.UV_VERSION }}

  ty:
    if: github.base_ref == 'dev' || github.base_ref == 'main'
    uses: ./.github/workflows/ty.yml
    with:
      python-version: ${{ vars.PYTHON_VERSION }}
      uv-version: ${{ vars.UV_VERSION }}

  tests:
    if: github.base_ref == 'dev' || github.base_ref == 'main'
    uses: ./.github/workflows/tests.yml
    with:
      python-version: ${{ vars.PYTHON_VERSION }}
      uv-version: ${{ vars.UV_VERSION }}