name: Tests

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      uv-version:
        required: true
        type: string

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-uv-project
        with:
          python-version: ${{ inputs.python-version }}
          uv-version: ${{ inputs.uv-version }}
          with-tests: 'true'
          all-extras: 'true'

      - name: Run tests
        run: uv run pytest